# Generated by Django 4.1 on 2024-02-12 07:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatar', max_length=255, verbose_name='image'),
        ),
    ]
