# Generated by Django 4.1 on 2024-02-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news_post',
            table='news_post',
        ),
    ]
